"""Creación de tablas iniciales

Revision ID: 66f445935f76
Revises: 
Create Date: 2024-11-10 01:48:35.247398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f445935f76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditorias_indicadores',
    sa.Column('id_auditoria', sa.Integer(), nullable=False),
    sa.Column('area_auditoria', sa.String(length=50), nullable=False),
    sa.Column('fecha_auditoria', sa.DateTime(), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('accion_correctiva', sa.Text(), nullable=True),
    sa.Column('indicador_desempeno', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_auditoria')
    )
    op.create_table('capacitaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tema', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('personal', sa.String(length=100), nullable=False),
    sa.Column('duracion_horas', sa.Integer(), nullable=True),
    sa.Column('evaluacion_final', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mejoras',
    sa.Column('id_mejora', sa.Integer(), nullable=False),
    sa.Column('no_conformidad', sa.Text(), nullable=False),
    sa.Column('accion_correctiva', sa.Text(), nullable=True),
    sa.Column('accion_preventiva', sa.Text(), nullable=True),
    sa.Column('fecha_implementacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_mejora')
    )
    op.create_table('no_conformidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_detectada', sa.Date(), nullable=False),
    sa.Column('responsable', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('accion_correctiva', sa.Text(), nullable=True),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partes_interesadas',
    sa.Column('id_interesado', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('necesidades_expectativas', sa.Text(), nullable=True),
    sa.Column('requisitos_identificados', sa.Text(), nullable=True),
    sa.Column('objetivo_estrategico', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_interesado')
    )
    with op.batch_alter_table('partes_interesadas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partes_interesadas_nombre'), ['nombre'], unique=True)

    op.create_table('procesos_operacion',
    sa.Column('id_proceso', sa.Integer(), nullable=False),
    sa.Column('proceso', sa.String(length=100), nullable=False),
    sa.Column('criterio_calidad', sa.Text(), nullable=True),
    sa.Column('control_proveedor', sa.Boolean(), nullable=True),
    sa.Column('no_conformidad', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_proceso')
    )
    with op.batch_alter_table('procesos_operacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procesos_operacion_proceso'), ['proceso'], unique=True)

    op.create_table('recursos_capacitacion',
    sa.Column('id_recurso', sa.Integer(), nullable=False),
    sa.Column('recurso_necesario', sa.Text(), nullable=False),
    sa.Column('capacitacion_personal', sa.Boolean(), nullable=True),
    sa.Column('descripcion_documentacion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_recurso')
    )
    op.create_table('riesgos_oportunidades',
    sa.Column('id_riesgo', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('Riesgo', 'Oportunidad', name='tipoenum'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('objetivo_calidad', sa.Text(), nullable=True),
    sa.Column('plan_accion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_riesgo')
    )
    op.create_table('roles_responsabilidades',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('compromiso_calidad', sa.Boolean(), nullable=True),
    sa.Column('descripcion_politica_calidad', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    with op.batch_alter_table('roles_responsabilidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_responsabilidades_rol'), ['rol'], unique=True)

    op.create_table('satisfaccion_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_encuesta', sa.Date(), nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('ADMINISTRADOR', 'AUDITOR', 'OPERATIVO', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('satisfaccion_cliente')
    with op.batch_alter_table('roles_responsabilidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_responsabilidades_rol'))

    op.drop_table('roles_responsabilidades')
    op.drop_table('riesgos_oportunidades')
    op.drop_table('recursos_capacitacion')
    with op.batch_alter_table('procesos_operacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procesos_operacion_proceso'))

    op.drop_table('procesos_operacion')
    with op.batch_alter_table('partes_interesadas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partes_interesadas_nombre'))

    op.drop_table('partes_interesadas')
    op.drop_table('no_conformidades')
    op.drop_table('mejoras')
    op.drop_table('capacitaciones')
    op.drop_table('auditorias_indicadores')
    # ### end Alembic commands ###
