"""Add documents table

Revision ID: 8dcf131930c5
Revises: cbde9ad8229b
Create Date: 2024-11-10 18:02:32.524341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dcf131930c5'
down_revision = 'cbde9ad8229b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('MANUAL_CALIDAD', 'PROCEDIMIENTO_OPERATIVO', 'INSTRUCCION_TRABAJO', 'PLAN_ACCION', 'OTRO', name='documentcategory'), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_code'))

    op.drop_table('documents')
    # ### end Alembic commands ###
