"""Adding Auditoria model

Revision ID: cbde9ad8229b
Revises: 66f445935f76
Create Date: 2024-11-10 13:52:28.642207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbde9ad8229b'
down_revision = '66f445935f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_auditada', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('auditor', sa.String(length=50), nullable=False),
    sa.Column('resultado', sa.Text(), nullable=False),
    sa.Column('accion_correctiva', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditorias')
    # ### end Alembic commands ###
